homework is done
AndrijKarmaza/node.js-homework pull request #1
Opened 2023-08-13 16:44 UTC by AndrijKarmaza

Доброго дня.
Перевірте, будь ласка

2023-08-13 18:02 UTC, ceREAL133 requested changes

2023-08-13 18:02 UTC, ceREAL133 commented on routes/api/contacts.js
> +  email: Joi.string().required(),
schema should be in separate file. You should validate email and phone properly

2023-08-13 18:02 UTC, ceREAL133 commented on routes/api/contacts.js
> +  try {
this functions should be defined in controller. Router should only invoke them

2023-08-14 10:09 UTC, AndrijKarmaza commented
fixed mistakes

2023-08-14 18:29 UTC, ceREAL133 approved these changes

2023-08-14 18:35 UTC, merged